# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.host_name = "debian"
  config.vm.network "private_network",
                    :ip => "172.10.10.5"
  config.vm.synced_folder "/var/cache/apt/archives",
                          "#{ENV["HOME"]}/.aptcache/jessie64",
                          :create => true,
                          :type => :nfs

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    # v.gui = true
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
end
